### ISSUE TITLE
Coalesce model validation fails when AppDbContext inherits from IdentityDbContext instead of DbContext

### ISSUE THREAD

**Issue by caseybarsness** [IntelliTect/Coalesce#35]
When using this DbContext:
`public class AppDbContext : IdentityDbContext` 

Coalesce code generation fails with this error:
` System.AggregateException: One or more errors occurred. (Object reference not set to an instance of an object.) ---> System.NullReferenceException: Object reference not set to an instance of an object.
   at IntelliTect.Coalesce.Validation.ValidateContext.Validate(ReflectionRepository repository)
   at IntelliTect.Coalesce.CodeGeneration.Generation.GenerationExecutor.<GenerateAsync>d__51.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at IntelliTect.Coalesce.Cli.Program.<>c__DisplayClass0_0.<<Main>b__1>d.MoveNext()
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
   at System.Threading.Tasks.Task1.GetResultCore(Boolean waitCompletionNotification)
   at Microsoft.Extensions.CommandLineUtils.CommandLineApplication.Execute(String[] args)
   at IntelliTect.Coalesce.Cli.Program.Main(String[] args)
---> (Inner Exception #0) System.NullReferenceException: Object reference not set to an instance of an object.
   at IntelliTect.Coalesce.Validation.ValidateContext.Validate(ReflectionRepository repository)
   at IntelliTect.Coalesce.CodeGeneration.Generation.GenerationExecutor.<GenerateAsync>d__51.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at IntelliTect.Coalesce.Cli.Program.<>c__DisplayClass0_0.<<Main>b__1>d.MoveNext()<---
`

**Comment by ascott18** [comment]
Funnily enough, you submitted this issue while the CI build for a fix for this issue was in progress. I happened to notice the exact same issue about 30 minutes prior. https://ci.appveyor.com/project/IntelliTect/coalesce/build/2.0.0-alpha-146

Fixed in a4a0bf7d, package version 2.0.0-alpha-148

**Comment by caseybarsness** [comment]
I have updated both nuget packages to 2.0.0-alpha-148 and still seem to be having the issue.

**Comment by ascott18** [comment]
Ok, I'll take a look tomorrow hopefully.

**Comment by ascott18** [comment]
(Did you make sure to update the tools package as well? There are three references in total to Coalesce package across your projects. Two of them are in the web .csproj)

**Comment by caseybarsness** [comment]
I did not see the tools reference in web.csproj!   I updated that and it fixed the issue!

Thank you!
